# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(420, 780)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.PlaylistContainer = QtWidgets.QListWidget(self.centralwidget)
        self.PlaylistContainer.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.PlaylistContainer.setEditTriggers(QtWidgets.QAbstractItemView.CurrentChanged|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.PlaylistContainer.setIconSize(QtCore.QSize(40, 40))
        self.PlaylistContainer.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.PlaylistContainer.setProperty("isWrapping", False)
        self.PlaylistContainer.setResizeMode(QtWidgets.QListView.Adjust)
        self.PlaylistContainer.setViewMode(QtWidgets.QListView.ListMode)
        self.PlaylistContainer.setUniformItemSizes(False)
        self.PlaylistContainer.setObjectName("PlaylistContainer")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Pictures/2colorthing.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        self.PlaylistContainer.addItem(item)
        self.verticalLayout_2.addWidget(self.PlaylistContainer)
        self.PlaybackControlls = QtWidgets.QGroupBox(self.centralwidget)
        self.PlaybackControlls.setFlat(False)
        self.PlaybackControlls.setObjectName("PlaybackControlls")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.PlaybackControlls)
        self.gridLayout_3.setContentsMargins(0, 0, 6, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.PlaylistInfo = QtWidgets.QLabel(self.PlaybackControlls)
        self.PlaylistInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.PlaylistInfo.setObjectName("PlaylistInfo")
        self.gridLayout_3.addWidget(self.PlaylistInfo, 3, 2, 1, 1)
        self.TrackLength = QtWidgets.QLabel(self.PlaybackControlls)
        self.TrackLength.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.TrackLength.setObjectName("TrackLength")
        self.gridLayout_3.addWidget(self.TrackLength, 2, 4, 1, 1)
        self.PlaybackSpeed = QtWidgets.QLabel(self.PlaybackControlls)
        self.PlaybackSpeed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PlaybackSpeed.setObjectName("PlaybackSpeed")
        self.gridLayout_3.addWidget(self.PlaybackSpeed, 3, 4, 1, 1)
        self.PlayButton = QtWidgets.QPushButton(self.PlaybackControlls)
        self.PlayButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("src/svg/play-circle-regular.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap("src/svg/pause-circle-regular.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap("src/svg/play-circle-solid.svg"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap("src/svg/pause-circle-solid.svg"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.PlayButton.setIcon(icon1)
        self.PlayButton.setIconSize(QtCore.QSize(64, 64))
        self.PlayButton.setCheckable(True)
        self.PlayButton.setDefault(False)
        self.PlayButton.setFlat(True)
        self.PlayButton.setObjectName("PlayButton")
        self.gridLayout_3.addWidget(self.PlayButton, 2, 2, 1, 1)
        self.NextButton = QtWidgets.QPushButton(self.PlaybackControlls)
        self.NextButton.setEnabled(True)
        self.NextButton.setMinimumSize(QtCore.QSize(0, 0))
        self.NextButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("src/svg/forward-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NextButton.setIcon(icon2)
        self.NextButton.setIconSize(QtCore.QSize(48, 48))
        self.NextButton.setFlat(True)
        self.NextButton.setObjectName("NextButton")
        self.gridLayout_3.addWidget(self.NextButton, 2, 3, 1, 1)
        self.PrevButton = QtWidgets.QPushButton(self.PlaybackControlls)
        self.PrevButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("src/svg/backward-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PrevButton.setIcon(icon3)
        self.PrevButton.setIconSize(QtCore.QSize(48, 48))
        self.PrevButton.setFlat(True)
        self.PrevButton.setObjectName("PrevButton")
        self.gridLayout_3.addWidget(self.PrevButton, 2, 1, 1, 1)
        self.PlaybackCurrentPosition = QtWidgets.QLabel(self.PlaybackControlls)
        self.PlaybackCurrentPosition.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.PlaybackCurrentPosition.setObjectName("PlaybackCurrentPosition")
        self.gridLayout_3.addWidget(self.PlaybackCurrentPosition, 2, 0, 1, 1)
        self.PlaybackSlider = QtWidgets.QSlider(self.PlaybackControlls)
        self.PlaybackSlider.setOrientation(QtCore.Qt.Horizontal)
        self.PlaybackSlider.setObjectName("PlaybackSlider")
        self.gridLayout_3.addWidget(self.PlaybackSlider, 1, 0, 1, 5)
        self.verticalLayout_2.addWidget(self.PlaybackControlls)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionPlay_Pause = QtWidgets.QAction(MainWindow)
        self.actionPlay_Pause.setCheckable(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("src/svg/play-circle-regular.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap("src/svg/pause-circle-regular.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon4.addPixmap(QtGui.QPixmap("src/svg/play-circle-solid.svg"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap("src/svg/pause-circle-solid.svg"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon4.addPixmap(QtGui.QPixmap("src/svg/play-circle-solid.svg"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap("src/svg/pause-circle-solid.svg"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.actionPlay_Pause.setIcon(icon4)
        self.actionPlay_Pause.setObjectName("actionPlay_Pause")
        self.TrackLength.setBuddy(self.PrevButton)

        self.retranslateUi(MainWindow)
        self.PlayButton.toggled['bool'].connect(self.actionPlay_Pause.trigger)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.PlaylistContainer.setSortingEnabled(True)
        __sortingEnabled = self.PlaylistContainer.isSortingEnabled()
        self.PlaylistContainer.setSortingEnabled(False)
        item = self.PlaylistContainer.item(0)
        item.setText(_translate("MainWindow", "dummy\n"
"hi"))
        self.PlaylistContainer.setSortingEnabled(__sortingEnabled)
        self.PlaylistInfo.setText(_translate("MainWindow", "TextLabel"))
        self.TrackLength.setText(_translate("MainWindow", "TextLabel"))
        self.PlaybackSpeed.setText(_translate("MainWindow", "TextLabel"))
        self.PlaybackCurrentPosition.setText(_translate("MainWindow", "TextLabel"))
        self.actionPlay_Pause.setText(_translate("MainWindow", "Play/Pause"))

